### ISSUE TITLE
darkent  fine-tune为nan

### ISSUE THREAD

**Issue by yyx1107** [PengyiZhang/SlimYOLOv3#13]
采用一个人手数据集，按照sr0.001进行稀疏训练，130epoch后
                                                                                  P            R            mAP      F1
126     0.0346  0.000206     0.203        15       416      0.364      0.699      0.547      0.479      0.351
127     0.0347   0.00022     0.203        13       416      0.364      0.699      0.547      0.479      0.351
128     0.0346   0.00025     0.203        12       416      0.364      0.699      0.547      0.479      0.351
129     0.0344  0.000321       0.2        20       416      0.364      0.699      0.547      0.479      0.351
130     0.0338  0.000247     0.198        12       416      0.388      0.678      0.538      0.494      0.355
 然后剪枝0.4，在darknet训练全是nan，大家是什么结果呀
是因为我没达到稀疏训练的效果吗？

**Comment by BeltonC** [comment]
你好，我想问下，在sparsity.py文件中,updateBN中第一个参数scale一般设为多少比较好呢?

**Comment by yyx1107** [comment]
> 你好，我想问下，在sparsity.py文件中,updateBN中第一个参数scale一般设为多少比较好呢?

他这篇论文里用的0.0001，我看论文里0.001和这个好像差不多。你的结果怎么样呀

**Comment by wjjouc** [comment]
@yyx1107 @BeltonC 
您好，请问您是否已经进行了Channel Prunning？我在运行以下命令时：
python yolov3/prune.py --cfg VisDrone2019/yolov3-spp3.cfg --weights yolov3-spp3_sparsity.weights 
出现了下面的问题：
Traceback (most recent call last):
  File "prune.py", line 389, in <module>
    opt.perlayer_ratio,
  File "prune.py", line 160, in test
    m = getattr(module, 'batch_norm_%d' % i) # batch_norm layer
  File "/home/wjj/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'batch_norm_0'
即使按照作者提供的办法，在prune.py文件中作出下面的改动：
-new_norm = getattr(new_module, 'batch_norm_%d' % i) 
+new_norm = getattr(new_module, 'BatchNorm2d')
问题依旧存在，无法解决，您知道该怎样解决这个问题吗？
另外，在下面的命令行中：
python yolov3/prune.py --cfg VisDrone2019/yolov3-spp3.cfg --data-cfg VisDrone2019/drone.data --weights yolov3-spp3_sparsity.weights --overall_ratio 0.5 --perlayer_ratio 0.1
好像--data-cfg VisDrone2019/drone.data这个参数在prune.py文件中并没有看到，是否可以省略掉--data-cfg VisDrone2019/drone.data？

**Comment by yyx1107** [comment]
> @yyx1107 @BeltonC
> 您好，请问您是否已经进行了Channel Prunning？我在运行以下命令时：
> python yolov3/prune.py --cfg VisDrone2019/yolov3-spp3.cfg --weights yolov3-spp3_sparsity.weights
> 出现了下面的问题：
> Traceback (most recent call last):
> File "prune.py", line 389, in
> opt.perlayer_ratio,
> File "prune.py", line 160, in test
> m = getattr(module, 'batch_norm_%d' % i) # batch_norm layer
> File "/home/wjj/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 535, in **getattr**
> type(self).**name**, name))
> AttributeError: 'Sequential' object has no attribute 'batch_norm_0'
> 即使按照作者提供的办法，在prune.py文件中作出下面的改动：
> -new_norm = getattr(new_module, 'batch_norm_%d' % i)
> +new_norm = getattr(new_module, 'BatchNorm2d')
> 问题依旧存在，无法解决，您知道该怎样解决这个问题吗？
> 另外，在下面的命令行中：
> python yolov3/prune.py --cfg VisDrone2019/yolov3-spp3.cfg --data-cfg VisDrone2019/drone.data --weights yolov3-spp3_sparsity.weights --overall_ratio 0.5 --perlayer_ratio 0.1
> 好像--data-cfg VisDrone2019/drone.data这个参数在prune.py文件中并没有看到，是否可以省略掉--data-cfg VisDrone2019/drone.data？

这是对应那个ul那个库里的.data文件，不可以省略，这个文件存的是这种格式：
classes= 2
train=data/custom/train.txt
valid=data/custom/valid.txt
names=data/custom/classes.names
类别数，存放训练集等的位置的文件以及类别名称

**Comment by wjjouc** [comment]
@yyx1107 
非常感谢您！
在运行prune.py时，我遇到了下面的问题：
Traceback (most recent call last):
File "prune.py", line 389, in
opt.perlayer_ratio,
File "prune.py", line 160, in test
m = getattr(module, 'batch_norm_%d' % i) # batch_norm layer
File "/home/wjj/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 535, in getattr
type(self).name, name))
AttributeError: 'Sequential' object has no attribute 'batch_norm_0'
您能告诉我该怎么解决这个问题吗？

**Comment by broliao** [comment]
@wjjouc 您好  我也遇到同样的问题，请问你是怎么解决的呢？

@yyx1107 您好，我有个疑惑，在prune.py中，剪枝后的测试程序，输入的是一张图片的路径，测试的时候只是拿这张图片来测试吗？我程序运行到测试这部分时出现错误。
![image](https://user-images.githubusercontent.com/49137103/65016215-4637fd00-d956-11e9-9f7b-1f16712e235f.png)
我程序运行时报错：
Traceback (most recent call last):
  File "D:/LJXpycharmproject/yolov3-slimyolov3/prune.py", line 398, in <module>
    opt.perlayer_ratio,
  File "D:/LJXpycharmproject/yolov3-slimyolov3/prune.py", line 346, in test
    inf_out, train_out = pruned_model(imgs)  # inference and training outputs
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\LJXpycharmproject\yolov3-slimyolov3\models.py", line 226, in forward
    x = torch.cat([layer_outputs[i] for i in layers], 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 20 and 40 in dimension 2 at C:/w/1/s/tmp_conda_3.6_041836/conda/conda-bld/pytorch_1556684464974/work/aten/src\THC/generic/THCTensorMath.cu:71

我参数设置是：
![image](https://user-images.githubusercontent.com/49137103/65016343-9911b480-d956-11e9-9e97-0106ea040bbc.png)
盼答复，谢谢！
