### ISSUE TITLE
pruning   error

### ISSUE THREAD

**Issue by hexiangquan** [PengyiZhang/SlimYOLOv3#23]
Traceback (most recent call last):
  File "/home/he/he/pytorch/SlimYOLOv3-master/yolov3/prune.py", line 381, in <module>
    opt.perlayer_ratio,
  File "/home/he/he/pytorch/SlimYOLOv3-master/yolov3/prune.py", line 272, in test
    new_norm = getattr(new_module, 'batch_norm_%d' % i)  # batch_norm layer
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'batch_norm_0'

**Comment by hexiangquan** [comment]
m = getattr(module, 'BatchNorm_%d' % i)  can not get thos attr
i run this CMD  Namespace(cfg='/opt/ultrared/new_4class/yolov3.cfg', img_size=512, overall_ratio=0.5, perlayer_ratio=0.1, save='prune_0.5_0.1', weights='converted.weights')

**Comment by zbyuan** [comment]
@hexiangquan  me  too，is it solved？

**Comment by PengyiZhang** [comment]
@hexiangquan @zbyuan 
I observe that [models.py](https://github.com/ultralytics/yolov3/blob/master/models.py) has been updated: 

From: 
```
            if bn:
                modules.add_module('batch_norm_%d' % i, nn.BatchNorm2d(filters))
```
To:

```
            if bn:
                modules.add_module('BatchNorm2d', nn.BatchNorm2d(filters, momentum=0.1))
```
So, you try to make modifications as below if latest  ultralytics/yolov3  is used
```
- new_norm = getattr(new_module, 'batch_norm_%d' % i) # batch_norm layer
+ new_norm = getattr(new_module, 'BatchNorm2d') # batch_norm layer
```

**Comment by Boinet** [comment]
Hi!
 Will you release a version with all dependencies soon? I can't run the pruning ... 
AttributeError: 'Sequential' object has no attribute 'batch_norm_0'
The above solution didn't solve it for me unfortunately...

**Comment by wjjouc** [comment]
@zbyuan @hexiangquan 
Have you solved this problem? I made  modifications as below：
-new_norm = getattr(new_module, 'batch_norm_%d' % i) # batch_norm layer
+new_norm = getattr(new_module, 'BatchNorm2d') # batch_norm layer
 but when I ran prune.py again the problem still appeared ：
AttributeError: 'Sequential' object has no attribute 'batch_norm_0'

**Comment by wjjouc** [comment]
@Boinet 
I meet the same problem as you even make modifications just like above
AttributeError: 'Sequential' object has no attribute 'batch_norm_0'
 Have you solved this problem?

**Comment by varghesealex90** [comment]
Traceback (most recent call last):
  File "prune.py", line 392, in <module>
    opt.perlayer_ratio,
  File "prune.py", line 271, in test
    pruned_model = Darknet(output_cfg_path, img_size).to(device)
  File "/src/slimyolov3/ktian/yolov3/models.py", line 174, in __init__
    self.module_defs = parse_model_cfg(cfg)
  File "/src/slimyolov3/ktian/yolov3/utils/parse_config.py", line 23, in parse_model_cfg
    mdefs[-1][key] = np.array([float(x) for x in val.split(',')]).reshape((-1, 2))  # np anchors
  File "/src/slimyolov3/ktian/yolov3/utils/parse_config.py", line 23, in <listcomp>
    mdefs[-1][key] = np.array([float(x) for x in val.split(',')]).reshape((-1, 2))  # np anchors
ValueError: could not convert string to float: ' [[         10          13]'

**Comment by varghesealex90** [comment]
Can someone please help with the above error

**Comment by wjjouc** [comment]
@varghesealex90 
I have met the same error with you. Have you already fix it？

**Comment by varghesealex90** [comment]
Yes. I think this error is due to using the master branch in ultralytics.

Clone to ultralytics 

and checkout to ktian branch
git checkout ktian

and then you wouldnt hopefully finding any issues

**Comment by zihaozhang9** [comment]
Does the question "AttributeError: 'Sequential' object has no attribute 'batch_norm_0'" progress? How to solve this problem?

I solved it as follows
`- new_norm = getattr(new_module, 'batch_norm_%d' % i) # batch_norm layer
+ new_norm = getattr(new_module, 'BatchNorm2d') # batch_norm layer`

Then I received the following error:

`layer: 125 yolo
Traceback (most recent call last):
  File "prune.py", line 390, in <module>
    opt.perlayer_ratio,
  File "prune.py", line 271, in test
    pruned_model = Darknet(output_cfg_path, img_size).to(device)
  File "/media/nnir712/F264A15264A119FD/zzh/detect/yolo/ul_slim/models.py", line 209, in __init__
    self.module_defs = parse_model_cfg(cfg)
  File "/media/nnir712/F264A15264A119FD/zzh/detect/yolo/ul_slim/utils/parse_config.py", line 22, in parse_model_cfg
    mdefs[-1][key] = np.array([float(x) for x in val.split(',')]).reshape((-1, 2))  # np anchors
  File "/media/nnir712/F264A15264A119FD/zzh/detect/yolo/ul_slim/utils/parse_config.py", line 22, in <listcomp>
    mdefs[-1][key] = np.array([float(x) for x in val.split(',')]).reshape((-1, 2))  # np anchors
ValueError: could not convert string to float: ' [[         10          13]'
`

**Comment by PiseyYou** [comment]
> Yes. I think this error is due to using the master branch in ultralytics.
> 
> Clone to ultralytics
> 
> and checkout to ktian branch
> git checkout ktian
> 
> and then you wouldnt hopefully finding any issues

now, need to  `git checkout ktian08-hyp`
but after python prune.py, still get these error.
```
Traceback (most recent call last):
  File "prune.py", line 389, in <module>
    opt.perlayer_ratio,
  File "prune.py", line 288, in test
    new_conv.weight.data = old_conv.weight.data[idx1.tolist()][:, idx2.tolist(), :, :].clone()
IndexError: too many indices for tensor of dimension 3
```
