### ISSUE TITLE
你好，可以提供vis2019转换完后的标签吗？

### ISSUE THREAD

**Issue by 92ypli** [PengyiZhang/SlimYOLOv3#27]

**Comment by 92ypli** [comment]
还有，怎么计算ap？

**Comment by wydwww** [comment]
You can use this [script](https://github.com/zhaobaiyu/visdrone/blob/master/darknet/scripts/visdrone_det_transform.py) to convert visdrone dataset to darknet format and get the label. 

Use `test.py` in https://github.com/ultralytics/yolov3 to test.

**Comment by 92ypli** [comment]
非常感谢你的工作，不过我觉得你有一些实验细节做的并不好，你直接用darknet训coco的anchor，并没有重新做聚类，如果重新做聚类ap应该会提高很多。

**Comment by wjjouc** [comment]
@wydwww 
Thank you very much for your solution. I wonder if you have completed the Channel Prunning. When I run:
python yolov3/prune.py --cfg VisDrone2019/yolov3-spp3.cfg  --weights yolov3-spp3_sparsity.weights
the following problem occur:
Traceback (most recent call last):
  File "prune.py", line 389, in <module>
    opt.perlayer_ratio,
  File "prune.py", line 160, in test
    m = getattr(module, 'batch_norm_%d' % i) # batch_norm layer
  File "/home/wjj/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'batch_norm_0'

Even though I have made the following changes in prune.py as described on the page https://github.com/PengyiZhang/SlimYOLOv3/issues/23:
-new_norm = getattr(new_module, 'batch_norm_%d' % i) 
+new_norm = getattr(new_module, 'BatchNorm2d') 
the problem still appeared as bellow:
AttributeError: 'Sequential' object has no attribute 'batch_norm_0'
Could you tell me how to solve this problem?

In addition, I have another question. When I run:
python yolov3/prune.py --cfg VisDrone2019/yolov3-spp3.cfg --data-cfg VisDrone2019/drone.data --weights yolov3-spp3_sparsity.weights
I didn't find "--data-cfg VisDrone2019/drone.data" in the prune.py as following:
if __name__ == '__main__':
    os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
    os.environ["CUDA_VISIBLE_DEVICES"] = "0"
    parser = argparse.ArgumentParser(description='PyTorch Slimming Yolov3 prune')
    parser.add_argument('--cfg', type=str, default='VisDrone2019/yolov3-spp3.cfg', help='cfg file path')
    parser.add_argument('--weights', type=str, default='yolov3-spp3_final.weights', help='path to weights file')
    parser.add_argument('--img_size', type=int, default=608, help='inference size (pixels)')
    parser.add_argument('--save', default='prune', type=str, metavar='PATH', help='path to save pruned model (default: none)')
    parser.add_argument('--overall_ratio', type=float, default=0.5, help='scale sparse rate (default: 0.5)')    
    parser.add_argument('--perlayer_ratio', type=float, default=0.1, help='minimal scale sparse rate (default: 0.1) to prevent disconnect')

Can we ignore "--data-cfg VisDrone2019/drone.data"?

**Comment by wydwww** [comment]
@wjjouc I didn't run the prune step.

**Comment by wjjouc** [comment]
@wydwww 
Thank you all the same. This problem has been bothering me for days.

**Comment by QuenceyTang** [comment]
> 非常感谢你的工作，不过我觉得你有一些实验细节做的并不好，你直接用darknet训coco的anchor，并没有重新做聚类，如果重新做聚类ap应该会提高很多。

anchor size影响不大吧。

**Comment by GinkgoX** [comment]
How to calculate the AP results?
