### ISSUE TITLE
I modified prune.py and sparsity syncing with newest version yolov3

### ISSUE THREAD

**Issue by erikguo** [PengyiZhang/SlimYOLOv3#37]
Hi All,

I modified prune.py and sparsity syncing with newest version yolov3. You can try.

[yolov3](https://github.com/erikguo/yolov3/tree/slimyolov3)

**Comment by QuenceyTang** [comment]
你好。请问prune.py 修改了哪里？

关于train.py， 我把updateBN定义在utils.py里然后按照作者的说法把updateBN(0.0001, model)加在了optimizer.step()前面。请问还有其他要改的吗？

**Comment by erikguo** [comment]
In prune.py, I changed name of BatchNorm and Conv.  Also, you can use train-sparsity.py to train.

**Comment by www12345678** [comment]
@erikguo
How to test with pruned models

**Comment by wjjouc** [comment]
@erikguo 
I run those commands:
git clone https://github.com/erikguo/yolov3.git
git checkout slimyolov3
python train-sparsity.py  --weights weights/darknet53.conv.74

the issue occurs as follow:
Traceback (most recent call last):
  File "train-sparsity.py", line 393, in <module>
    results = train()
  File "train-sparsity.py", line 270, in train
    loss, loss_items = compute_loss(pred, targets, model)
  File "/home/gc/4-images/9.4/jiehe/yolov3/utils/utils.py", line 320, in compute_loss
    arc = model.arc  # # (default, uCE, uBCE) detection architectures
  File "/home/gc/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'Darknet' object has no attribute 'arc'

but I run : python train.py ,everything goes well
How should I fix this issue?

**Comment by erikguo** [comment]
@wjjouc 

Could you show your running command with train-spasity.py?

**Comment by erikguo** [comment]
@wjjouc 

your running command is wrong:
```
    python train-sparsity.py --weights weights/darknet53.conv.74
```

please change the command as following:
```
python train-sparsity.py --cfg ./yolov3-spp3.cfg --data ./obj.data --weights weights/darknet53.conv.74
```

**Comment by CharlesYXW** [comment]
@erikguo I use the command just like what you say,but I also catch this problem:
  File "train-sparsity.py", line 393, in <module>
    results = train()
  File "train-sparsity.py", line 271, in train
    loss, loss_items = compute_loss(pred, targets, model)
  File "/home/amax/yxw/prune/yolov3-slimyolov3/utils/utils.py", line 320, in compute_loss
    arc = model.arc  # # (default, uCE, uBCE) detection architectures
  File "/home/amax/anaconda3/envs/ame/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'Darknet' object has no attribute 'arc'
Please tell me how to solve it,thank you!

**Comment by erikguo** [comment]
Please give me your command. I will try similarly tonight. @CharlesYXW

**Comment by erikguo** [comment]
I updated the lastest version yolov3, deleted train-sparsity.py, merged the sparsity training into train.py.   

You can use train.py --sparsity 0.0001 to do the training.

@CharlesYXW  And I have try the newest version. It's running very well. So I didn't repeat your error  . I think you should give me more information.

**Comment by CharlesYXW** [comment]
Yeah，I just do the same thing as you do this afternoon，and I have solved the problem.I am sorry that I didn't see your reply. Thank you ！ ------------------ 原始邮件 ------------------
发件人: "erikguo"<notifications@github.com>
发送时间: 2019年9月5日(星期四) 晚上9:45
收件人: "PengyiZhang/SlimYOLOv3"<SlimYOLOv3@noreply.github.com>;
抄送: "CharlesYXW"<506385585@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [PengyiZhang/SlimYOLOv3] I modified prune.py and sparsity syncingwith newest version yolov3 (#37)



I updated the lastest version yolov3, deleted train-sparsity.py, merged the sparsity training into train.py.
 
You can use train.py --sparsity 0.0001 to do the training.
 
@CharlesYXW  And I have try the newest version. It's running very well. So I didn't repeat your error  . I think you should give me more information.
 
&mdash;

**Comment by broliao** [comment]
@erikguo can you provide your test  result or your sparsity training mode?I really want to know that,thanks a lot.

**Comment by fengsong77** [comment]
> Hi All,
> 
> I modified prune.py and sparsity syncing with newest version yolov3. You can try.
> 
> [yolov3](https://github.com/erikguo/yolov3/tree/slimyolov3)
建议scale修改为opt.scale或直接定义一个超参数，如下：
# x_{k+1} = x_{k} - \alpha_{k} * g^{k}
def updateBN(opt.scale, model):
    for m in model.modules():
        if isinstance(m, nn.BatchNorm2d):
            m.weight.grad.data.add_(scale*torch.sign(m.weight.data))  # L1
------------------------------------------------------------
parser.add_argument('--scale', type=float, default=1e-4)

**Comment by broliao** [comment]
@CharlesYXW hi,have you run the prune.py?I get the follow error,could you tell me how to run it,or how to solve it.thank you very much,this error have bother me a few day.

Traceback (most recent call last):
  File "D:/LJXpycharmproject/yolov3-slimyolov3/prune.py", line 398, in <module>
    opt.perlayer_ratio,
  File "D:/LJXpycharmproject/yolov3-slimyolov3/prune.py", line 346, in test
    inf_out, train_out = pruned_model(imgs)  # inference and training outputs
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\LJXpycharmproject\yolov3-slimyolov3\models.py", line 226, in forward
    x = torch.cat([layer_outputs[i] for i in layers], 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 20 and 40 in dimension 2 at C:/w/1/s/tmp_conda_3.6_041836/conda/conda-bld/pytorch_1556684464974/work/aten/src\THC/generic/THCTensorMath.cu:71

**Comment by May-forever** [comment]
> Hi All,
> 
> I modified prune.py and sparsity syncing with newest version yolov3. You can try.
> 
> [yolov3](https://github.com/erikguo/yolov3/tree/slimyolov3)

师兄，你好，@erikguo。很感谢你能开源代码。

我有三个问题想咨询一下，先谢谢师兄了

这个代码是不是将Slim-yolo以及ultralytics/yolov3集成在了一起？换句话说，是不是直接用你的代码就可以实现Slim-yolo以及ultralytics/yolov3两个工程的功能

我可以在windows上运行这个代码吗？有什么需要注意的地方？

我自己设计了一个网络，并在AlexyAB的darknet上训练过了，我想和师兄咨询一下，我自己的网络可以用你的框架进行剪枝优化吗？

期待你的回信，先谢谢师兄了。

**Comment by May-forever** [comment]
> Hi All,
> 
> I modified prune.py and sparsity syncing with newest version yolov3. You can try.
> 
> [yolov3](https://github.com/erikguo/yolov3/tree/slimyolov3)

Hi, @erikguo,

I use your repro to slim my network (not yolov3) on windows 10. However, an error occur as shown below, what should I do ?please give me a hand.
![1](https://user-images.githubusercontent.com/20625075/66894135-3f1e1080-f022-11e9-8c3d-99cb253e967d.png)

**Comment by Spectra456** [comment]
> > Hi All,
> > I modified prune.py and sparsity syncing with newest version yolov3. You can try.
> > [yolov3](https://github.com/erikguo/yolov3/tree/slimyolov3)
> 
> Hi, @erikguo,
> 
> I use your repro to slim my network (not yolov3) on windows 10. However, an error occur as shown below, what should I do ?please give me a hand.
> ![1](https://user-images.githubusercontent.com/20625075/66894135-3f1e1080-f022-11e9-8c3d-99cb253e967d.png)

Hi, i'm trying to prune yolov3, but when i'm launching model i got this:
  = torch.cat([layer_outputs[i] for i in layers], 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 94 and 190 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71
Can you help me?
